name: Continuous Builds

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16, 18, 20]
        runner: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: action/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run pack
      - uses: actions/upload-artifact@v3
        with:
          name: bindings
          path: build/binding
